const fs = require('fs');
const path = require('path');

const shellPath = path.join(__dirname, '..', 'dist', 'shell.html');
const outPath = path.join(__dirname, '..', 'src', 'shellHtml.ts');

if (!fs.existsSync(shellPath)) {
  console.error('dist/shell.html not found — run vite build first');
  process.exit(1);
}

let content = fs.readFileSync(shellPath, 'utf-8');
// Escape backticks, dollar signs, and backslashes for template literal
content = content.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\${/g, '\\${');

fs.writeFileSync(outPath, `// Auto-generated by scripts/inline-shell.cjs — do not edit manually
export const SHELL_HTML = \`${content}\`;
`);
console.log('Generated src/shellHtml.ts');
