// Auto-generated by scripts/inline-shell.cjs — do not edit manually
export const SHELL_HTML = `<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Gittymon: Turn any GitHub profile into a savage 8-bit Roast-mon</title>
    <meta name="description" content="Turn any GitHub profile into a savage 8-bit Roast-mon monster — battle bugs, fight AI bosses, and climb the leaderboard. All inside a retro Gameboy shell." />

    <!-- Open Graph -->
    <meta property="og:title" content="Gittymon — Summon Your Profile Monster" />
    <meta property="og:description" content="Enter a GitHub username and the app summons a unique Roast-mon monster with stats, moves, a savage AI roast, and custom 8-bit pixel art — then battle it in a Gameboy-styled arena." />
    <!-- OG_IMAGE_INJECTED_BY_SERVER -->
    <meta property="og:image:width" content="1280" />
    <meta property="og:image:height" content="640" />
    <meta property="og:image:type" content="image/png" />
    <!-- OG_URL_INJECTED_BY_SERVER -->
    <meta property="og:type" content="website" />
    <meta property="og:site_name" content="Gittymon" />

    <!-- Twitter Card -->
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="twitter:title" content="Gittymon — Summon Your Profile Monster" />
    <meta name="twitter:description" content="Enter a GitHub username and the app summons a unique Roast-mon monster with stats, moves, a savage AI roast, and custom 8-bit pixel art — all inside a retro Gameboy shell." />
    <!-- TWITTER_IMAGE_INJECTED_BY_SERVER -->

    <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
    <script type="module" crossorigin src="/assets/index-DijoFd9H.js"></script>
    <link rel="stylesheet" crossorigin href="/assets/index-CzBkjZ9f.css">
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
`;
